version: "3"

services:
  blue:
    image: bluegreen-app:latest
    environment:
      - APP_VERSION=blue
    ports:
      - "3001:3000"

  green:
    image: bluegreen-app:latest
    environment:
      - APP_VERSION=green
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/upstream_app.conf:/etc/nginx/conf.d/upstream_app.conf
    depends_on:
      - blue
      - green
